CXX = g++
CXXFLAGS = -std=c++14 -Wall -g -MMD
EXEC = a1q1
OBJECTS = a1q1.o process.o
DEPENDS = ${OBJECTS:.o=.d}

${EXEC}: ${OBJECTS}
	${CXX} ${OBJECTS} -o ${EXEC}

-include ${DEPENDS}

.PHONY: clean

clean:
	rm ${OBJECTS} ${EXEC} ${DEPENDS}

