CXX = g++
CXXFLAGS = -std=c++14 -g -MMD
EXEC = runSuite
OBJECTS = a1q4.o filehelpers.o
DEPENDS = ${OBJECTS:.o=.d}

${EXEC}: ${OBJECTS}
	${CXX} ${OBJECTS} -o ${EXEC}

-include ${DEPENDS}

.PHONY: clean

clean:
	rm ${OBJECTS} ${EXEC} ${DEPENDS}

